name       : python-sparqlwrapper
version    : 1.8.5
release    : 6
source     :
    - https://github.com/RDFLib/sparqlwrapper/archive/1.8.5.tar.gz : f7c5fa05f101ac8a77aac5a479d381c384651152f33df85da2d8b76586470c6a
license    : W3C # https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document
component  : programming.python
summary    : A wrapper for a remote SPARQL endpoint
description: |
    A wrapper for a remote SPARQL endpoint
builddeps  :
    - pkgconfig(python3)
    - python-nose
rundeps    :
    - python-nose
build      : |
    %python3_setup
install    : |
    %python3_install
