name       : python-sparqlwrapper
version    : 2.0.0
release    : 8
source     :
    - https://github.com/RDFLib/sparqlwrapper/releases/download/2.0.0/SPARQLWrapper-2.0.0.tar.gz : 3fed3ebcc77617a4a74d2644b86fd88e0f32e7f7003ac7b2b334c026201731f1
license    : W3C # https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document
component  : programming.python
summary    : A wrapper for a remote SPARQL endpoint
description: |
    A wrapper for a remote SPARQL endpoint
builddeps  :
    - pkgconfig(python3)
    - python-nose
rundeps    :
    - python-nose
build      : |
    %python3_setup
install    : |
    %python3_install
