name       : python-sparqlwrapper
version    : 1.7.6
release    : 1
source     :
    - https://github.com/RDFLib/sparqlwrapper/archive/1.7.6.tar.gz : 8bbe74edf46c33ed4bf40c67b89d40d2259325ab2b78b0c0238a44c88ed1bed7
license    : W3C # https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document
component  : programming.python
summary    : A wrapper for a remote SPARQL endpoint
description: |
    A wrapper for a remote SPARQL endpoint
builddeps  :
    - pkgconfig(python-2.7)
    - python-nose
    - python-setuptools
rundeps    :
    - python-nose
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
