name       : python-sparqlwrapper
version    : 1.8.4
release    : 3
source     :
    - https://github.com/RDFLib/sparqlwrapper/archive/1.8.4.tar.gz : 936109a68bd2adc09dec8ae69f83c262a97cb16f079908ee97c05fabb5bf3913
license    : W3C # https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document
component  : programming.python
summary    : A wrapper for a remote SPARQL endpoint
description: |
    A wrapper for a remote SPARQL endpoint
builddeps  :
    - pkgconfig(python3)
    - python-nose
rundeps    :
    - python-nose
build      : |
    %python3_setup
install    : |
    %python3_install
